# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Afladagbokin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Afladagbokin

  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'
  pod 'StokkurUtls', :git => 'https://bitbucket.org/stokkur/stokkurutls.git'
  pod 'Bond', '6.5.2'
  pod 'SwiftKeychainWrapper'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Phone'
  pod 'SVProgressHUD', '2.2.2'
  pod 'ReachabilitySwift'
  pod 'lottie-ios'

  target 'AfladagbokinTests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!

    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'
    pod 'StokkurUtls', :git => 'https://bitbucket.org/stokkur/stokkurutls.git'
    pod 'Bond', '6.5.2'
    pod 'SwiftKeychainWrapper'
    pod 'Firebase/Core'
  end
end
